#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WMS_Android.Resource", IsApplication=true)]

namespace WMS_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::WMS_Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::WMS_Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::WMS_Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_press = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int red_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedButton = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060019
			public const int btnAdd = 2131099673;
			
			// aapt resource value: 0x7f060005
			public const int btnExit = 2131099653;
			
			// aapt resource value: 0x7f06002a
			public const int btnLogin = 2131099690;
			
			// aapt resource value: 0x7f06000b
			public const int btnNext = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int btnNextPO = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int btnNextSkuForPO = 2131099651;
			
			// aapt resource value: 0x7f06001a
			public const int btnReceive = 2131099674;
			
			// aapt resource value: 0x7f060007
			public const int btnScan = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int btnScanBin = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int btnScanSku = 2131099671;
			
			// aapt resource value: 0x7f060008
			public const int btnSelectPO = 2131099656;
			
			// aapt resource value: 0x7f06001c
			public const int btnShip = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int btnStock = 2131099675;
			
			// aapt resource value: 0x7f06002b
			public const int contentFrame = 2131099691;
			
			// aapt resource value: 0x7f06000a
			public const int frameLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int gvCtrl = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int horizontalPOInfo = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int horizontalSkuInfo = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int lblPONUmber = 2131099661;
			
			// aapt resource value: 0x7f060027
			public const int lblPassword = 2131099687;
			
			// aapt resource value: 0x7f06000f
			public const int lblSkuNUmber = 2131099663;
			
			// aapt resource value: 0x7f060025
			public const int lblUsername = 2131099685;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout2 = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout3 = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060016
			public const int txtBinNumber = 2131099670;
			
			// aapt resource value: 0x7f060029
			public const int txtLoginMessage = 2131099689;
			
			// aapt resource value: 0x7f06001f
			public const int txtLot1 = 2131099679;
			
			// aapt resource value: 0x7f060012
			public const int txtLotNumber = 2131099666;
			
			// aapt resource value: 0x7f060023
			public const int txtOpenClosed = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int txtPO = 2131099680;
			
			// aapt resource value: 0x7f060024
			public const int txtPO1 = 2131099684;
			
			// aapt resource value: 0x7f060009
			public const int txtPONumber = 2131099657;
			
			// aapt resource value: 0x7f060028
			public const int txtPassword = 2131099688;
			
			// aapt resource value: 0x7f060011
			public const int txtQuanity = 2131099665;
			
			// aapt resource value: 0x7f060022
			public const int txtQuantity = 2131099682;
			
			// aapt resource value: 0x7f06001e
			public const int txtQuantity1 = 2131099678;
			
			// aapt resource value: 0x7f060018
			public const int txtSku = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int txtSku1 = 2131099677;
			
			// aapt resource value: 0x7f060010
			public const int txtSkuNumber = 2131099664;
			
			// aapt resource value: 0x7f060026
			public const int txtUsername = 2131099686;
			
			// aapt resource value: 0x7f060021
			public const int txtVendor = 2131099681;
			
			// aapt resource value: 0x7f060014
			public const int verticalPOInfo = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConfirmReceived = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EnterPO = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EnterQuantityAndLot = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EnterSku = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EnterStock = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Home = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListBinnedStock = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListPurchaseOrder = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListStock = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Login = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040022
			public const int Add = 2130968610;
			
			// aapt resource value: 0x7f040005
			public const int ApplicationName = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int DatabaseFileName = 2130968583;
			
			// aapt resource value: 0x7f04000e
			public const int DefaultBinText = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int DefaultPOText = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int DefaultSkuText = 2130968591;
			
			// aapt resource value: 0x7f040000
			public const int EnterBinMessage = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int EnterLotNumberColon = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int EnterManuallyMessage = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int EnterPO = 2130968584;
			
			// aapt resource value: 0x7f040016
			public const int EnterQuantityColon = 2130968598;
			
			// aapt resource value: 0x7f04000a
			public const int EnterSku = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int EnterStock = 2130968585;
			
			// aapt resource value: 0x7f040018
			public const int ExitMessage = 2130968600;
			
			// aapt resource value: 0x7f04001c
			public const int IncorrectUserPassword = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int Login = 2130968603;
			
			// aapt resource value: 0x7f04000b
			public const int LotNumber = 2130968587;
			
			// aapt resource value: 0x7f040012
			public const int Next = 2130968594;
			
			// aapt resource value: 0x7f040017
			public const int NextPOMessage = 2130968599;
			
			// aapt resource value: 0x7f040021
			public const int NextSkuForPO = 2130968609;
			
			// aapt resource value: 0x7f040010
			public const int PONumber = 2130968592;
			
			// aapt resource value: 0x7f040014
			public const int PONumberId = 2130968596;
			
			// aapt resource value: 0x7f04001a
			public const int PasswordColon = 2130968602;
			
			// aapt resource value: 0x7f040015
			public const int PlaceHolder = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int Quantity = 2130968595;
			
			// aapt resource value: 0x7f04001e
			public const int Receive = 2130968606;
			
			// aapt resource value: 0x7f040001
			public const int ScanBinMessage = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ScanButtonMessage = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ScanSku = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int ScannedBarcode = 2130968582;
			
			// aapt resource value: 0x7f04001d
			public const int SelectPO = 2130968605;
			
			// aapt resource value: 0x7f040020
			public const int Ship = 2130968608;
			
			// aapt resource value: 0x7f040011
			public const int SkuNumber = 2130968593;
			
			// aapt resource value: 0x7f04001f
			public const int Stock = 2130968607;
			
			// aapt resource value: 0x7f040019
			public const int UsernameColon = 2130968601;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
